name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        java: [ 'openjdk@1.11' ]
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      # - name: Coursier cache
      #   uses: coursier/cache-action@v6
      - name: Set current version
        run:  echo "ADDON_VERSION=$(cat version.sbt | grep version | cut -d= -f2 | xargs)" >> $GITHUB_ENV
      - name: sbt make-pkg (${{ env.ADDON_VERSION }})
        run: sbt make-pkg
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: sbt docker:publish (${{ env.ADDON_VERSION }})
        run: sbt addon/docker:publish
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: SwissQR Addon ${{ env.ADDON_VERSION }}
          gzip: false
          draft: false
          prerelease: false
          allow_override: false
          files: >
            modules/addon/target/addon/swissqr-addon-${{ env.ADDON_VERSION }}.zip
